---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: l2INWwsqWAwopaN4UvrJMz29AeD6doIRjDsSLqPSFW2c9fdmoW8jwaZr8srIDABoaO1mSiokW1FlVMFyrcG5Xx1P/8iXG9ZGmUWpcG8Vh9ytBwp7M4SiFTLjZQcJouburfcDYyqz0MZiGT3dWCOnD8q7H5MBU1CYJ/yQzhyR2qCTCZ7X2Eq05LTsu6PBCNiJvoL1QFSblZ8VGB1FZs9FoVCRfSmj8f1gvJFkoTjsU7n38Fz0Pj2BrSQ3svAVt5SVmBuwMcY8QkYOG9foroFqQ1WLdBWO1VzmlI758Y4dE+p4zURDJB4ILgnp0Iyv3rR2/DF18MgtdLk5eU8buHnLWU1yZz2RcecrCk/aJ4r40Bn1X7f37JGQWrv+zfXFaaKzhU3PAIGa6yEJ6e/tokl8+/R3kSk05XUEncbuL9foVA0BELWrrhWrSk6MTbI6rxMAQavnkVrDpBV8gsnDZkiha6J3MpIGcOZxmjN8hK0/7NH+xU96q4USZQcurxTPE+W91gMx3R3VkFLDrtBmyvm5MTG06qraAVtX/zcXBPgyk4UjGAvGzDEUE+PnjgLp51rdo9Gg5dJV7kftRY29PmlkiTjcFpTX+R4GQR1csinPeHz4ngNArgnCSCfWs37jg4/z+4XwFvO8MBtYMvKwoo+U0V+ESTcJvyupz4BNKmW6Y5c=
